name: Deploy to IPFS

on:
  push:
    branches:
      - main  # Déclencher lors d'un push sur la branche principale
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Déployer sur IPFS via Pinata
      - name: IPFS Pinata deploy GitHub action
        uses: popovoleksandr/ipfs-pinata-deploy-action@v1.6.3
        with:
          pin-name: 'My personal site'
          path: './build'
          pinata_api_key: 2aa10484b328530809c5
          pinata_secret_api_key: 0e3270c63bb662a9b966a5c15cd2d13fe3854ea606c5b1521ec17e084b706eb6
          verbose: true
