name: Deploy to IPFS
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Doing test deploy to Pinata
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Pinata deploy action step
        id: deploy
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.3
        with:
          pin-name: 'My personal site'
          path: './.github/workflows/site2test'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY}}
          verbose: true
          remove-old: false
